name: build-and-test

on:
  pull_request:
    branches: [main]
jobs:
  build_and_test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        rosdistro:
          - humble

    runs-on: ubuntu-latest

    container:
      image: ros:${{ matrix.rosdistro }}-ros-base

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: wheel_stuck_ws

      - name: Install dependencies
        run: |
          cd wheel_stuck_ws &&
          rosdep update &&
          apt-get update &&
          vcs import src < depend_packages_ci.repos &&
          rosdep install --from-path . -i -y --rosdistro ${{ matrix.rosdistro }}

      - name: Install diagnostic-updater
        run: apt-get install ros-${{ matrix.rosdistro }}-diagnostic-updater

      - name: Build tests
        id: build_test
        run: |
          . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
          colcon build --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        continue-on-error: true

      - name: build_test command success
        if: steps.build_test.outcome == 'success'
        run: echo "result - success"

      - name: build_test command failure
        if: steps.build_test.outcome == 'failure'
        run: echo "result - failure" && exit 1

      - name: Run tests
        id: run_test
        run: |
          . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
          colcon test &&
          colcon test-result
        continue-on-error: true

      - name: run_test command success
        if: steps.run_test.outcome == 'success'
        run: echo "result - success"

      - name: run_test command failure
        if: steps.run_test.outcome == 'failure'
        run: echo "result - failure" && exit 1

      - name: Install clang-tidy
        run: apt-get install clang-tidy

      - name: Merge compile_commands.json
        run: |
          python3 .github/merge_compile_commands.py

      - name: Run clang-tidy
        run: |
          clang-tidy -p compile_commands.json find src/ -name "*.cpp"
        continue-on-error: true
