name: label-check

on:
  workflow_call:
    inputs:
      label:
        required: true
        type: string
    outputs:
      result:
        value: ${{ jobs.label-check.outputs.result }}

jobs:
  label-check:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.label-check.outputs.result }}
    steps:
      - name: Check if the PR is labeled
        id: label-check
        if: contains(github.event.pull_request.labels.*.name, inputs.label)
        run: |
          echo "result=true" >> $GITHUB_OUTPUT
        shell: bash

      - name: Skip if the PR is not labeled
        if: steps.label-check.outputs.result != 'true'
        run: |
          echo "Add the label '${{ inputs.label }}' to continue this workflow."
          echo "result=false" >> $GITHUB_OUTPUT
        shell: bash
