name: spell-check

on:
  pull_request:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Run spell check
        uses: streetsidesoftware/cspell-action@v6
        with:
          config: .cspell.json
          incremental_files_only: true
